In [24]:
import pandas as pd

In [25]:
df = pd.read_csv(r"C:\Users\MY LAPTOP\OneDrive\Desktop\Machine_Learning\Customer Segmentation\jumia_dataset.csv")
df

,Product_Name,Category,Current_Price,Old_Price,Discount,Total_Ratings,Image_Link,Review_Rating,Review_Date,Verified_Purchase,Review_Text
0,Philly 20000mAh Power Charging Bank Type-C Input,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 8,490","₦ 13,875",39%,(12459 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,5 out of 5,No Date,Yes,Portable in size
1,Philly 20000mAh Power Charging Bank Type-C Input,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 8,490","₦ 13,875",39%,(12459 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,5 out of 5,No Date,Yes,Very durable
2,Philly 20000mAh Power Charging Bank Type-C Input,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 8,490","₦ 13,875",39%,(12459 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,5 out of 5,No Date,Yes,It has the quality as expected
3,Philly 20000mAh Power Charging Bank Portable C...,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 7,752","₦ 13,057",41%,(18675 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,1 out of 5,No Date,Yes,Strong and powerful. Been using for a year
4,Philly 20000mAh Power Charging Bank Portable C...,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 7,752","₦ 13,057",41%,(18675 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,5 out of 5,No Date,Yes,Always on full bar
...,...,...,...,...,...,...,...,...,...,...,...
2707,Oraimo PowerTrans USB-C Hub 7-in-1 Multi-Funct...,Home > Computing > Computers > Networking Prod...,"₦ 24,000","₦ 37,500",36%,(13 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,4 out of 5,No Date,Yes,As advertised
2708,Danami Men's Plain Round Neck T-Shirt- White,Home > Fashion > Men's Fashion > Clothing > Sh...,"₦ 6,900 - ₦ 7,900",No Old Price,0%,(587 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,4 out of 5,No Date,Yes,Good enough
2709,Danami Men's Plain Round Neck T-Shirt- White,Home > Fashion > Men's Fashion > Clothing > Sh...,"₦ 6,900 - ₦ 7,900",No Old Price,0%,(587 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,5 out of 5,No Date,Yes,Perfect
2710,Danami Men's Plain Round Neck T-Shirt- White,Home > Fashion > Men's Fashion > Clothing > Sh...,"₦ 6,900 - ₦ 7,900",No Old Price,0%,(587 verified ratings),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,5 out of 5,No Date,Yes,The top isn't bad
2711,Trendyol Knitted Casual Dress - Mink,Home > Fashion > Women's Fashion > Clothing > ...,"₦ 3,735 - ₦ 7,935","₦ 17,000",78%,(1 verified rating),https://ng.jumia.is/unsafe/fit-in/300x300/filt...,No Rating,No Date,No,No comments

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2712 entries, 0 to 2711
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Product_Name       2712 non-null   object
 1   Category           2712 non-null   object
 2   Current_Price      2712 non-null   object
 3   Old_Price          2712 non-null   object
 4   Discount           2712 non-null   object
 5   Total_Ratings      2712 non-null   object
 6   Image_Link         2712 non-null   object
 7   Review_Rating      2712 non-null   object
 8   Review_Date        2712 non-null   object
 9   Verified_Purchase  2712 non-null   object
 10  Review_Text        2709 non-null   object
dtypes: object(11)
memory usage: 233.2+ KB

In [27]:
df.columns

Index(['Product_Name', 'Category', 'Current_Price', 'Old_Price', 'Discount',
       'Total_Ratings', 'Image_Link', 'Review_Rating', 'Review_Date',
       'Verified_Purchase', 'Review_Text'],
      dtype='object')

In [28]:
jumia_data = df.drop(['Image_Link', 'Review_Date'], axis=1)

In [29]:
jumia_data.dropna()

,Product_Name,Category,Current_Price,Old_Price,Discount,Total_Ratings,Review_Rating,Verified_Purchase,Review_Text
0,Philly 20000mAh Power Charging Bank Type-C Input,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 8,490","₦ 13,875",39%,(12459 verified ratings),5 out of 5,Yes,Portable in size
1,Philly 20000mAh Power Charging Bank Type-C Input,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 8,490","₦ 13,875",39%,(12459 verified ratings),5 out of 5,Yes,Very durable
2,Philly 20000mAh Power Charging Bank Type-C Input,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 8,490","₦ 13,875",39%,(12459 verified ratings),5 out of 5,Yes,It has the quality as expected
3,Philly 20000mAh Power Charging Bank Portable C...,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 7,752","₦ 13,057",41%,(18675 verified ratings),1 out of 5,Yes,Strong and powerful. Been using for a year
4,Philly 20000mAh Power Charging Bank Portable C...,Home > Phones & Tablets > Mobile Phone Accesso...,"₦ 7,752","₦ 13,057",41%,(18675 verified ratings),5 out of 5,Yes,Always on full bar
...,...,...,...,...,...,...,...,...,...
2707,Oraimo PowerTrans USB-C Hub 7-in-1 Multi-Funct...,Home > Computing > Computers > Networking Prod...,"₦ 24,000","₦ 37,500",36%,(13 verified ratings),4 out of 5,Yes,As advertised
2708,Danami Men's Plain Round Neck T-Shirt- White,Home > Fashion > Men's Fashion > Clothing > Sh...,"₦ 6,900 - ₦ 7,900",No Old Price,0%,(587 verified ratings),4 out of 5,Yes,Good enough
2709,Danami Men's Plain Round Neck T-Shirt- White,Home > Fashion > Men's Fashion > Clothing > Sh...,"₦ 6,900 - ₦ 7,900",No Old Price,0%,(587 verified ratings),5 out of 5,Yes,Perfect
2710,Danami Men's Plain Round Neck T-Shirt- White,Home > Fashion > Men's Fashion > Clothing > Sh...,"₦ 6,900 - ₦ 7,900",No Old Price,0%,(587 verified ratings),5 out of 5,Yes,The top isn't bad
2711,Trendyol Knitted Casual Dress - Mink,Home > Fashion > Women's Fashion > Clothing > ...,"₦ 3,735 - ₦ 7,935","₦ 17,000",78%,(1 verified rating),No Rating,No,No comments

In [30]:
rating_map = {
    '5 out of 5': 'good',
    '4 out of 5': 'good',
    '3 out of 5': 'average',
    '2 out of 5': 'bad',
    '1 out of 5': 'bad'
}

jumia_data['Review_Rating'] = jumia_data['Review_Rating'].map(rating_map).fillna('bad')

In [31]:
jumia_data['Category'].unique()

array(['Home > Phones & Tablets > Mobile Phone Accessories > Batteries & Battery Packs > Portable Power Banks',
       'Home > Home & Office > Home & Kitchen > Heaters, Air Cooling & Purification > Household Fans > Standing Fans',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Blenders > Personal Size Blenders',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Deodorants & Antiperspirants > Antiperspirants',
       'Home > Home & Office > Small & Cooking Appliances > Small Appliances > Ironing & Laundry',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Air Fryers',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Body > Moisturizers & Body Lotions > Lotions',
       'Home > Home & Office > Large Appliances & Home Improvement > Large Appliances > Fridges',
       'Home > Phones & Tablets > Mobile Phones > Basic Phones > Cell Phones',
       'Home > Home & Office > Small & Cooking Appliances > Small Appliances > Kettles > Electric Kettles',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Body > Moisturizers & Body Lotions',
       'Home > Electronics > Television & Video > Televisions > LED & LCD TVs',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Deodorants & Antiperspirants',
       'Home > Phones & Tablets > Mobile Phones > Smartphones > Android Phones',
       'Home > Electronics > Television & Video > Televisions > Smart TVs',
       'Home > Home & Office > Small & Cooking Appliances > Cooking Appliances > Table & Cooktop > Gas > Glass Top',
       'Home > Health & Beauty > Beauty & Personal Care > Hair Care > Hair Cutting Tools > Hair Clippers & Accessories',
       'Home > Phones & Tablets > Mobile Phone Accessories > Bluetooth Headsets',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Sunscreens & Tanning Products > Sunscreens > Facial Sunscreens',
       'Home > Home & Office > Large Appliances & Home Improvement > Large Appliances > Washing Machines & Dryers > Washing Machines',
       'Home > Home & Office > Home & Kitchen > Heaters, Air Cooling & Purification > Household Fans > Rechargeable Fans',
       "Home > Fashion > Men's Fashion > Shoes > Fashion Sneakers > Sneakers > Low-cut",
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Body > Cleansers > Soaps',
       'Home > Phones & Tablets > Mobile Phone Accessories > Bluetooth Accessories > Headsets',
       'Home > Phones & Tablets > Mobile Phone Accessories > Selfie Sticks & Tripods > Selfie Sticks',
       'Home > Health & Beauty > Beauty & Personal Care > Hair Care > Hair Cutting Tools > Hair Clippers & Accessories > Hair Clippers',
       'Home > Home & Office > Small & Cooking Appliances > Small Appliances > Mixing & Blending > Mixers & Blenders',
       'Home > Home & Office > Large Appliances & Home Improvement > Large Appliances > Freezers > Deep Freezers',
       'Home > Garden & Outdoors > Generators & Portable Power > Power Stations',
       "Home > Health & Beauty > Beauty & Personal Care > Personal Care > Shave & Hair Removal > Women's Grooming > Shaving Creams, Lotions & Gels",
       'Home > Phones & Tablets > Mobile Phone Accessories > Smart Watches',
       "Home > Fashion > Men's Fashion > Clothing > Underwear > Boxers",
       'Home > Health & Beauty > Personal Care > Skin Care > Body > Moisturizers > Creams',
       'Home > Home & Office > Home & Kitchen > Lighting & Ceiling Fans > Lamps & Shades > Lamp Sets',
       'Home > Phones & Tablets > Mobile Phones',
       'Home > Home & Office > Home & Kitchen > Bath > Bathroom Accessories > Holders & Dispensers > Soap Dishes',
       "Home > Fashion > Men's Fashion > Shoes > Fashion Sneakers > Sneakers > High-top",
       "Home > Fashion > Men's Fashion > Shoes > Sandals",
       'Home > Home & Office > Large Appliances & Home Improvement > Power & Hand Tools > Hand Tools > Screwdrivers & Nut Drivers > Screwdriver Sets',
       "Home > Fashion > Men's Fashion > Clothing > Shirts > T-Shirts",
       'Home > Home & Office > Large Appliances & Home Improvement > Large Appliances > Washing Machines & Dryers',
       'Home > Home & Office > Large Appliances & Home Improvement > Large Appliances > Air Conditioners & Accessories > Air Conditioners > Split-System',
       'Home > Home & Office > Home & Kitchen > Irons & Steamers > Irons',
       "Home > Fashion > Men's Fashion > Clothing > T-Shirts & Tanks > T-shirts",
       "Home > Fashion > Women's Fashion > Handbags & Wallets > Handbags > Tote Bags",
       'Home > Health & Beauty > Personal Care > Skin Care > Body > Cleansers > Soaps',
       "Home > Fashion > Men's Fashion > Shoes > Casual",
       'Home > Electronics > Television & Video > Televisions > 50 - 65 Inches TVs',
       'Home > Health & Beauty > Personal Care > Skin Care > Body > Cleansers > Body Washes',
       'Home > Phones & Tablets > Mobile Phone Accessories > Portable Speakers & Audio Docks > Portable Bluetooth Speakers',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Blenders > Countertop Blenders',
       "Home > Fashion > Women's Fashion > Shoes > Sandals > Heeled Sandals",
       'Home > Home & Office > Small & Cooking Appliances > Cooking Appliances > Cookers > Gas Cookers',
       'Home > Garden & Outdoors > Generators & Portable Power > Solar & Wind Power > Solar Battery Chargers & Charging Kits',
       'Home > Garden & Outdoors > Generators & Portable Power > Solar & Wind Power > Solar Panels',
       'Home > Grocery > Beverages > Coffee, Tea & Cocoa > Cocoa',
       "Home > Fashion > Multi-Pack > Men's Bundles > Men's Clothing Bundle",
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Microwave Ovens',
       'Home > Computing > Computers > Networking Products > Routers',
       'Home > Health & Beauty > Beauty & Personal Care > Oral Care > Toothpaste',
       'Home > Computing > Computers > Data Storage > USB Flash Drives',
       "Home > Fashion > Men's Fashion > Clothing > Shirts > Polos",
       'Home > Home & Office > Large Appliances & Home Improvement > Large Appliances > Air Conditioners & Accessories > Air Conditioners',
       'Home > Phones & Tablets > Mobile Phone Accessories > Bluetooth Accessories > Speakers',
       "Home > Fashion > Men's Fashion > Clothing > Shirts > Casual Button-Down Shirts > Patterned",
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Deodorants & Antiperspirants > Deodorants',
       'Home > Phones & Tablets > Mobile Phone Accessories > Earphones & Headsets',
       "Home > Fashion > Men's Fashion > Clothing > Underwear > Boxers > Sets",
       "Home > Fashion > Women's Fashion > Shoes > Fashion Sneakers",
       "Home > Fashion > Women's Fashion > Clothing > Dresses > Casual Dresses",
       "Home > Fashion > Men's Fashion > Shoes > Loafers & Slip-Ons",
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Body > Cleansers',
       "Home > Fashion > Men's Fashion > Shoes > Boots > Hiking",
       "Home > Fashion > Men's Fashion > Clothing > Pants",
       'Home > Grocery > Food Cupboard > Cooking Ingredients > Cubes & Stocks',
       "Home > Fashion > Men's Fashion > Shoes > Formal Shoes > Slip on",
       'Home > Home & Office > Home & Kitchen > Home Decor > Clocks > Wall Clocks',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Ovens & Toasters > Toasters',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Blenders > Hand Blenders',
       "Home > Health & Beauty > Beauty & Personal Care > Fragrances > Women's > Eau de Parfum",
       "Home > Fashion > Men's Fashion > Shoes > Sandals > Slides",
       'Home > Phones & Tablets > Mobile Phone Accessories > Chargers & Power Adapters > Wall Chargers',
       "Home > Fashion > Men's Fashion > Clothing > Jackets & Coats > Lightweight Jackets > Denim",
       'Home > Phones & Tablets > Tablets > Android Tablets',
       'Home > Home & Office > Large Appliances & Home Improvement > Large Appliances > Freezers',
       "Home > Fashion > Men's Fashion > Clothing > T-Shirts & Tanks > Vests",
       "Home > Fashion > Women's Fashion > Jewelry > Fashion > Bracelets",
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Blenders',
       'Home > Electronics > Television & Video > Televisions > Digital TVs',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Food Processors',
       "Home > Fashion > Men's Fashion > Shoes > Sandals > Sling Back",
       'Home > Garden & Outdoors > Generators & Portable Power > Generators',
       "Home > Fashion > Men's Fashion > Clothing > Socks > Casual Socks",
       'Home > Electronics > Accessories & Supplies > Batteries, Chargers & Accessories > Power Extension Sockets',
       "Home > Health & Beauty > Beauty & Personal Care > Fragrances > Men's > Eau de Parfum",
       'Home > Health & Beauty > Personal Care > Skin Care > Body > Cleansers',
       'Home > Health & Beauty > Sexual Wellness > Contraceptives & Lubricants > Condoms',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Body > Moisturizers & Body Lotions > Oils',
       'Home > Home & Office > Home & Kitchen > Heaters, Air Cooling & Purification > Household Fans > Pedestal Fans',
       "Home > Fashion > Men's Fashion > Clothing > Pants > Casual > Joggers",
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Microwave Ovens > Compact Microwave Ovens',
       "Home > Fashion > Women's Fashion > Shoes > Slippers",
       "Home > Health & Beauty > Beauty & Personal Care > Fragrances > Women's > Body Sprays",
       "Home > Fashion > Women's Fashion > Clothing > Dresses",
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Body > Moisturizers & Body Lotions > Body Butter',
       "Home > Fashion > Men's Fashion > Shoes > Sandals > Flip flops",
       'Home > Grocery > Drinks > Beer, Wine & Spirits > Spirits & Liquors > Whiskey',
       "Home > Fashion > Men's Fashion > Clothing > Shirts",
       'Home > Grocery > Beverages > Bottled Beverages, Water & Drink Mixes > Soft Drinks',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Face > Cleansers',
       'Home > Health & Beauty > Beauty & Personal Care > Hair Care > Hair Cutting Tools > Hair Clippers & Accessories > Accessories > Trimmer & Clipper Blades',
       'Home > Phones & Tablets > Mobile Phone Accessories > Data & Connectivity > Data Cables',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Cookware > Cookware Accessories',
       "Home > Health & Beauty > Beauty & Personal Care > Personal Care > Shave & Hair Removal > Men's Grooming > Nose & Ear Hair Trimmers",
       "Home > Fashion > Men's Fashion > Underwear & Sleepwear > Underwear",
       'Home > Sporting Goods > Sports & Fitness > Sport Clothing > Men > Athletic Supporters',
       'Home > Phones & Tablets > Mobile Phones > Smartphones',
       'Home > Automobile > Car Electronics & Accessories > Car Electronics > Installation Accessories & Harnesses > Amplifier Installation > Cooling Fans',
       'Home > Automobile > Motorcycle & Powersports > Accessories > Battery Chargers',
       "Home > Fashion > Men's Fashion > Clothing > Fashion Hoodies & Sweatshirts > Fashion Hoodies > Overhead",
       'Home > Electronics > Accessories & Supplies > Power Protection > Stabilizers',
       "Home > Fashion > Men's Fashion > Clothing > Underwear > Boxer Briefs",
       "Home > Fashion > Men's Fashion > Shoes > Outdoor > Rain Footwear > Rain Boots",
       'Home > Phones & Tablets > Telephones & Accessories > VoIP > Routers',
       "Home > Fashion > Men's Fashion > Shoes > Formal Shoes > Lace up",
       'Home > Electronics > Headphones > Earbud Headphones',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Dining & Entertaining > Plates > Dinner Plates',
       'Home > Grocery > Dried Beans, Grains & Rice > Rice & Grains',
       "Home > Fashion > Kid's Fashion > Girls > Clothing",
       'Home > Health & Beauty > Beauty & Personal Care > Hair Care > Hair Cutting Tools > Hair Clippers & Accessories > Finishing Trimmers',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Lip Care > Lip Balms & Treatments',
       'Home > Musical Instruments > Microphones & Accessories > Microphones > Wireless Microphones & Systems > Wireless Lavalier Microphones',
       'Home > Electronics > Television & Video > Streaming Media Players',
       'Home > Fashion > Shoe, Jewelry & Watch Accessories > Jewelry Accessories > Jewelry Boxes & Organizers > Jewelry Boxes',
       "Home > Fashion > Men's Fashion > Shoes > Work & Safety > Industrial & Construction",
       'Home > Health & Beauty > Personal Care > Skin Care > Body > Moisturizers > Body Butter',
       "Home > Fashion > Women's Fashion > Clothing > Pants > Trouser",
       'Home > Fashion > Luggage & Travel Gear > Laptop Bags > Shoulder Bags',
       'Home > Electronics > Home Audio > Speakers > Bluetooth Speakers',
       "Home > Fashion > Men's Fashion > Clothing > Shorts > Cargo",
       "Home > Fashion > Men's Fashion > Clothing > Pants > Casual",
       "Home > Fashion > Men's Fashion > Shoes > Slippers",
       'Home > Home & Office > Home & Office Furniture > Lighting > Lighting Bulbs & Component > Lighting Bulb > Energy Saving',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Ovens & Toasters > Toaster Ovens',
       "Home > Fashion > Men's Fashion > Clothing > Jackets & Coats > Lightweight Jackets",
       "Home > Fashion > Men's Fashion > Jewelry > Necklaces",
       'Home > Electronics > Home Appliances > Household Appliances > Irons & Steamers > Steam Irons (With Cord)',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Water Coolers & Filters > Water Filter Cleaners',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Electric Pressure Cookers',
       "Home > Health & Beauty > Beauty & Personal Care > Fragrances > Men's > Body Sprays",
       'Home > Home & Office > Small & Cooking Appliances > Small Appliances > Vacuum Cleaners',
       "Home > Fashion > Men's Fashion > Shoes > Fashion Sneakers > Canvas > Low-cut",
       'Home > Grocery > Household Cleaning > Cleaning Tools > Mopping > Buckets',
       'Home > Health & Beauty > Beauty & Personal Care > Fragrances > Solid Perfumes',
       'Home > Home & Office > Home & Kitchen > Home Decor > Artificial Plants > Artificial Flowers',
       "Home > Fashion > Men's Fashion > Clothing > Fashion Hoodies & Sweatshirts > Fashion Hoodies",
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Face > Creams & Moisturizers',
       'Home > Home & Office > Home & Kitchen > Lighting & Ceiling Fans > Lamps & Shades > Table Lamps',
       'Home > Grocery > Laundry > Powder Detergent',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Dining & Entertaining > Bowls > Bowl Sets',
       'Home > Health & Beauty > Beauty & Personal Care > Personal Care > Skin Care > Sunscreens & Tanning Products > Sunscreens',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Small Appliances > Coffee, Tea & Espresso Appliances > Electric Kettles',
       'Home > Home & Office > Large Appliances & Home Improvement > Large Appliances',
       'Home > Home & Office > Home & Kitchen > Kitchen & Dining > Cookware > Steamers, Stock & Pasta Pots > Steamers',
       "Home > Fashion > Men's Fashion > Shoes > Boots",
       'Home > Health & Beauty > Health Care > First Aid > Antibacterial & Antiseptics',
       "Home > Fashion > Men's Fashion > Shoes > Mules & Clogs",
       'Home > Sporting Goods > Sports & Fitness > Accessories > Gym Bags > Sports Duffels',
       "Home > Fashion > Women's Fashion > Clothing > Tops & Tees > Blouses & Button-Down Shirts",
       "Home > Fashion > Women's Fashion > Clothing > Shorts",
       "Home > Fashion > Men's Fashion > Clothing > Men's Sportswear > Active Shorts",
       'Home > Grocery > Food Cupboard > Pasta & Noodles > Pasta > Small Packs',
       "Home > Fashion > Women's Fashion > Handbags & Wallets > Handbags",
       'Home > Grocery > Beverages > Bottled Beverages, Water & Drink Mixes > Milk & Cream',
       "Home > Fashion > Men's Fashion > Clothing > T-Shirts & Tanks > Henleys",
       'Home > Computing > Computer Accessories > Keyboards, Mice & Accessories > Mice',
       'Home > Grocery > Laundry > Detergent Pacs & Tablets',
       'Home > Grocery > Household Supplies > Laundry > Bar Soap Detergent',
       'Home > Lotions',
       'Home > Home & Office > Small & Cooking Appliances > Small Appliances > Other Small Appliances',
       'Home > Phones & Tablets > Mobile Phone Accessories > Mounts & Stands > Stands',
       'Home > Health & Beauty > Beauty & Personal Care > Oral Care > Toothbrushes > Electric Toothbrushes',
       "Home > Fashion > Kid's Fashion > Boys > Shops > School Uniforms > Clothing > Shorts",
       "Home > Health & Beauty > Personal Care > Shave & Hair Removal > Men's > Electric Shavers > Rotary Shavers",
       'Home > Electronics > Home Audio > Home Theater Systems > Speakers',
       'Home > Fashion > Luggage & Travel Gear > Laptop Bags > Backpacks',
       'Home > Home & Office > Home & Kitchen > Home Decor > Candles & Holders > Candles > Scented Candles',
       'Home > Electronics > Accessories & Supplies > Power Protection > Surge Protectors',
       'Home > Phones & Tablets > Mobile Phone Accessories > Chargers > Wall Chargers',
       "Home > Fashion > Women's Fashion > Jewelry > Fashion > Bracelets > Bangle",
       'Home > Computing > Computers > Laptops & Desktops > Laptops',
       'Home > Health & Beauty > Oral Care > Toothpaste',
       'Home > Home & Office > Large Appliances & Home Improvement > Light Bulbs > Compact Fluorescent Bulbs',
       "Home > Fashion > Men's Fashion > Clothing > Men's Sportswear > Active Hoodies",
       'Home > Electronics > Home Audio > Home Theater Systems > Sound Bars',
       'Home > Home & Office > Small & Cooking Appliances > Small Appliances > Ironing & Laundry > Dry Iron',
       'Home > Grocery > Household Cleaning > Bathroom Cleaners > Toilet Cleaners',
       'Home > Garden & Outdoors > Generators & Portable Power > Power Inverters',
       "Home > Fashion > Men's Fashion > Clothing > Men's Sportswear > Active Shirts & Tees > Plain",
       'Home > Health & Beauty > Personal Care > Deodorants & Antiperspirants > Deodorants',
       'Home > Health & Beauty > Personal Care > Skin Care > Body > Moisturizers',
       "Home > Fashion > Men's Fashion > Clothing > Fashion Hoodies & Sweatshirts > Fashion Sweatshirts > Crew",
       'Home > Grocery > Food Cupboard > Cooking Oil',
       "Home > Fashion > Men's Fashion > Clothing > Shorts",
       'Home > Electronics > Wearable Technology > Headphones',
       'Home > Computing > Computer Accessories > USB Gadgets > USB Fans',
       'Home > Health & Beauty > Beauty & Personal Care > Tools & Accessories > Feet, Hand & Nail Tools > Sets & Kits',
       'Home > Computing > Computers > Laptops & Desktops > Laptops > 2 in 1 Laptops',
       "Home > Fashion > Women's Fashion > Shoes > Oxfords",
       'Home > Home & Office > Small & Cooking Appliances > Small Appliances > Kettles',
       'Home > Home & Office > Home & Kitchen > Irons & Steamers > Garment Steamers',
       'Home > Health & Beauty > Beauty & Personal Care > Tools & Accessories > Feet, Hand & Nail Tools > Nail Clippers > Fingernail Clippers',

In [32]:
jumia_data['Category'] = df['Category']

def get_third_category(cat_string):
    if isinstance(cat_string, str):
        parts = cat_string.split(' > ')
        return parts[2] if len(parts) > 2 else None
    return None

jumia_data['Sub_Category'] = jumia_data['Category'].apply(get_third_category)

display(jumia_data[['Category', 'Sub_Category']].dropna().head())

                                            Category              Sub_Category
0  Home > Phones & Tablets > Mobile Phone Accesso...  Mobile Phone Accessories
1  Home > Phones & Tablets > Mobile Phone Accesso...  Mobile Phone Accessories
2  Home > Phones & Tablets > Mobile Phone Accesso...  Mobile Phone Accessories
3  Home > Phones & Tablets > Mobile Phone Accesso...  Mobile Phone Accessories
4  Home > Phones & Tablets > Mobile Phone Accesso...  Mobile Phone Accessories

In [33]:
jumia_data['Sub_Category'].unique()

array(['Mobile Phone Accessories', 'Home & Kitchen',
       'Beauty & Personal Care', 'Small & Cooking Appliances',
       'Large Appliances & Home Improvement', 'Mobile Phones',
       'Television & Video', "Men's Fashion",
       'Generators & Portable Power', 'Personal Care', "Women's Fashion",
       'Beverages', 'Multi-Pack', 'Computers', 'Food Cupboard', 'Tablets',
       'Accessories & Supplies', 'Sexual Wellness', 'Drinks',
       'Sports & Fitness', 'Car Electronics & Accessories',
       'Motorcycle & Powersports', 'Telephones & Accessories',
       'Headphones', 'Dried Beans, Grains & Rice', "Kid's Fashion",
       'Microphones & Accessories', 'Shoe, Jewelry & Watch Accessories',
       'Luggage & Travel Gear', 'Home Audio', 'Home & Office Furniture',
       'Home Appliances', 'Household Cleaning', 'Laundry', 'Health Care',
       'Computer Accessories', 'Household Supplies', None, 'Oral Care',
       'Wearable Technology'], dtype=object)

In [34]:
jumia_data['Category'] = jumia_data['Sub_Category']

In [35]:
jumia_data.drop(['Sub_Category'], axis=1, inplace=True)

In [36]:
cols_to_clean = ['Current_Price', 'Old_Price', 'Discount']

for col in cols_to_clean:
    jumia_data[col] = jumia_data[col].astype(str).str.replace(r'[₦%,]', '', regex=True).str.strip()

display(jumia_data[cols_to_clean].head())

  Current_Price Old_Price Discount
0          8490     13875       39
1          8490     13875       39
2          8490     13875       39
3          7752     13057       41
4          7752     13057       41

In [37]:
jumia_data

,Product_Name,Category,Current_Price,Old_Price,Discount,Total_Ratings,Review_Rating,Verified_Purchase,Review_Text
0,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490,13875,39,(12459 verified ratings),good,Yes,Portable in size
1,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490,13875,39,(12459 verified ratings),good,Yes,Very durable
2,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490,13875,39,(12459 verified ratings),good,Yes,It has the quality as expected
3,Philly 20000mAh Power Charging Bank Portable C...,Mobile Phone Accessories,7752,13057,41,(18675 verified ratings),bad,Yes,Strong and powerful. Been using for a year
4,Philly 20000mAh Power Charging Bank Portable C...,Mobile Phone Accessories,7752,13057,41,(18675 verified ratings),good,Yes,Always on full bar
...,...,...,...,...,...,...,...,...,...
2707,Oraimo PowerTrans USB-C Hub 7-in-1 Multi-Funct...,Computers,24000,37500,36,(13 verified ratings),good,Yes,As advertised
2708,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,6900 - 7900,No Old Price,0,(587 verified ratings),good,Yes,Good enough
2709,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,6900 - 7900,No Old Price,0,(587 verified ratings),good,Yes,Perfect
2710,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,6900 - 7900,No Old Price,0,(587 verified ratings),good,Yes,The top isn't bad
2711,Trendyol Knitted Casual Dress - Mink,Women's Fashion,3735 - 7935,17000,78,(1 verified rating),bad,No,No comments

In [38]:
import unicodedata
import sys

punctuation = dict.fromkeys(i for i in range(sys.maxunicode)if unicodedata.category(chr(i)).startswith('P'))

jumia_data['Review_Text'] = [str(string).translate(punctuation) for string in jumia_data['Review_Text']]

In [40]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\MY
[nltk_data]     LAPTOP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [41]:
from nltk.tokenize import word_tokenize

nltk.download('stopwords')
nltk.download('punkt_tab')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

jumia_data['Review_Text'] = jumia_data['Review_Text'].apply(word_tokenize)

[nltk_data] Downloading package stopwords to C:\Users\MY
[nltk_data]     LAPTOP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\MY
[nltk_data]     LAPTOP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [42]:
jumia_data['Review_Text'] = jumia_data['Review_Text'].apply(lambda x: [word for word in x if word.lower() not in stop_words])

In [43]:
from nltk.stem.porter import PorterStemmer
jumia_data['Review_Text'] = jumia_data['Review_Text'].apply(lambda x: [PorterStemmer().stem(word) for word in x])

In [44]:
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
jumia_data['Review_Text'] = jumia_data['Review_Text'].apply(lambda x: [WordNetLemmatizer().lemmatize(word) for word in x])

[nltk_data] Downloading package wordnet to C:\Users\MY
[nltk_data]     LAPTOP\AppData\Roaming\nltk_data...

In [45]:
jumia_data['Review_Text']

0                  [portabl, size]
1                         [durabl]
2                [qualiti, expect]
3       [strong, power, use, year]
4               [alway, full, bar]
                   ...
2707                    [advertis]
2708                [good, enough]
2709                     [perfect]
2710              [top, isnt, bad]
2711                     [comment]
Name: Review_Text, Length: 2712, dtype: object

In [46]:
import re

jumia_data['Total_Ratings'] = jumia_data['Total_Ratings'].astype(str).str.extract('(\d+)').astype(int)

display(jumia_data[['Total_Ratings']].head())

   Total_Ratings
0          12459
1          12459
2          12459
3          18675
4          18675

In [47]:
jumia_data

,Product_Name,Category,Current_Price,Old_Price,Discount,Total_Ratings,Review_Rating,Verified_Purchase,Review_Text
0,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490,13875,39,12459,good,Yes,"[portabl, size]"
1,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490,13875,39,12459,good,Yes,[durabl]
2,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490,13875,39,12459,good,Yes,"[qualiti, expect]"
3,Philly 20000mAh Power Charging Bank Portable C...,Mobile Phone Accessories,7752,13057,41,18675,bad,Yes,"[strong, power, use, year]"
4,Philly 20000mAh Power Charging Bank Portable C...,Mobile Phone Accessories,7752,13057,41,18675,good,Yes,"[alway, full, bar]"
...,...,...,...,...,...,...,...,...,...
2707,Oraimo PowerTrans USB-C Hub 7-in-1 Multi-Funct...,Computers,24000,37500,36,13,good,Yes,[advertis]
2708,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,6900 - 7900,No Old Price,0,587,good,Yes,"[good, enough]"
2709,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,6900 - 7900,No Old Price,0,587,good,Yes,[perfect]
2710,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,6900 - 7900,No Old Price,0,587,good,Yes,"[top, isnt, bad]"
2711,Trendyol Knitted Casual Dress - Mink,Women's Fashion,3735 - 7935,17000,78,1,bad,No,[comment]

In [48]:
def parse_price(price_str):
    if isinstance(price_str, str):
        price_str = price_str.strip()
        if ' - ' in price_str:
            try:
                low, high = map(float, price_str.split(' - '))
                return (low + high) / 2
            except ValueError:
                return None
        elif price_str == 'No Old Price':
            return None
        else:
            try:
                return float(price_str)
            except ValueError:
                return None
    return price_str
jumia_data['Current_Price'] = jumia_data['Current_Price'].apply(parse_price)
jumia_data['Old_Price'] = jumia_data['Old_Price'].apply(parse_price)

jumia_data['Discount'] = pd.to_numeric(jumia_data['Discount'], errors='coerce')

display(jumia_data[['Current_Price', 'Old_Price', 'Discount']].head())
display(jumia_data[['Current_Price', 'Old_Price', 'Discount']].info())

   Current_Price  Old_Price  Discount
0         8490.0    13875.0        39
1         8490.0    13875.0        39
2         8490.0    13875.0        39
3         7752.0    13057.0        41
4         7752.0    13057.0        41

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2712 entries, 0 to 2711
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Current_Price  2712 non-null   float64
 1   Old_Price      2528 non-null   float64
 2   Discount       2712 non-null   int64
dtypes: float64(2), int64(1)
memory usage: 63.7 KB

None

In [49]:
jumia_data

,Product_Name,Category,Current_Price,Old_Price,Discount,Total_Ratings,Review_Rating,Verified_Purchase,Review_Text
0,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490.0,13875.0,39,12459,good,Yes,"[portabl, size]"
1,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490.0,13875.0,39,12459,good,Yes,[durabl]
2,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490.0,13875.0,39,12459,good,Yes,"[qualiti, expect]"
3,Philly 20000mAh Power Charging Bank Portable C...,Mobile Phone Accessories,7752.0,13057.0,41,18675,bad,Yes,"[strong, power, use, year]"
4,Philly 20000mAh Power Charging Bank Portable C...,Mobile Phone Accessories,7752.0,13057.0,41,18675,good,Yes,"[alway, full, bar]"
...,...,...,...,...,...,...,...,...,...
2707,Oraimo PowerTrans USB-C Hub 7-in-1 Multi-Funct...,Computers,24000.0,37500.0,36,13,good,Yes,[advertis]
2708,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,7400.0,NaN,0,587,good,Yes,"[good, enough]"
2709,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,7400.0,NaN,0,587,good,Yes,[perfect]
2710,Danami Men's Plain Round Neck T-Shirt- White,Men's Fashion,7400.0,NaN,0,587,good,Yes,"[top, isnt, bad]"
2711,Trendyol Knitted Casual Dress - Mink,Women's Fashion,5835.0,17000.0,78,1,bad,No,[comment]

In [50]:
jumia_data.dropna()

,Product_Name,Category,Current_Price,Old_Price,Discount,Total_Ratings,Review_Rating,Verified_Purchase,Review_Text
0,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490.0,13875.0,39,12459,good,Yes,"[portabl, size]"
1,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490.0,13875.0,39,12459,good,Yes,[durabl]
2,Philly 20000mAh Power Charging Bank Type-C Input,Mobile Phone Accessories,8490.0,13875.0,39,12459,good,Yes,"[qualiti, expect]"
3,Philly 20000mAh Power Charging Bank Portable C...,Mobile Phone Accessories,7752.0,13057.0,41,18675,bad,Yes,"[strong, power, use, year]"
4,Philly 20000mAh Power Charging Bank Portable C...,Mobile Phone Accessories,7752.0,13057.0,41,18675,good,Yes,"[alway, full, bar]"
...,...,...,...,...,...,...,...,...,...
2704,Oraimo PowerDock 15W Magnetic Wireless Chargin...,Mobile Phone Accessories,16995.0,22500.0,24,6,good,Yes,"[good, product, charg, fast, doesnt, heat, muc..."
2705,Oraimo PowerTrans USB-C Hub 7-in-1 Multi-Funct...,Computers,24000.0,37500.0,36,13,good,Yes,"[expect, like, design]"
2706,Oraimo PowerTrans USB-C Hub 7-in-1 Multi-Funct...,Computers,24000.0,37500.0,36,13,good,Yes,[work]
2707,Oraimo PowerTrans USB-C Hub 7-in-1 Multi-Funct...,Computers,24000.0,37500.0,36,13,good,Yes,[advertis]
2711,Trendyol Knitted Casual Dress - Mink,Women's Fashion,5835.0,17000.0,78,1,bad,No,[comment]

In [51]:
from sklearn.model_selection import train_test_split

X = jumia_data.drop(['Review_Rating'], axis=1)
y = jumia_data['Review_Rating']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score


X_train_text = X_train['Review_Text'].apply(lambda x: ' '.join(x) if isinstance(x, list) and x else '<EMPTY_REVIEW>')
X_test_text = X_test['Review_Text'].apply(lambda x: ' '.join(x) if isinstance(x, list) and x else '<EMPTY_REVIEW>')

vectorizer = TfidfVectorizer(ngram_range=(1, 2), max_features=5000)

X_train_vec = vectorizer.fit_transform(X_train_text)
X_test_vec = vectorizer.transform(X_test_text)

In [53]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

print("Overall Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Overall Accuracy: 0.8158379373848987

Classification Report:

              precision    recall  f1-score   support

     average       1.00      0.03      0.05        37
         bad       0.82      0.31      0.45        86
        good       0.82      0.99      0.89       420

    accuracy                           0.82       543
   macro avg       0.88      0.44      0.47       543
weighted avg       0.83      0.82      0.77       543

In [54]:
jumia_data['Review_Rating'].value_counts()

Review_Rating
good       2177
bad         341
average     194
Name: count, dtype: int64

In [55]:
custom_weights = {
    'good': 0.10,
    'bad': 0.40,
    'average': 0.50
}

In [56]:
log = LogisticRegression(max_iter=1000, random_state=42, class_weight=custom_weights)

log.fit(X_train_vec, y_train)
y_pred = log.predict(X_test_vec)

print("Overall Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

report = classification_report(y_test, y_pred)
report_dict = classification_report(y_test, y_pred, output_dict=True)

report_dict

Overall Accuracy: 0.8139963167587477

Classification Report:

              precision    recall  f1-score   support

     average       0.14      0.03      0.05        37
         bad       0.74      0.37      0.50        86
        good       0.83      0.97      0.90       420

    accuracy                           0.81       543
   macro avg       0.57      0.46      0.48       543
weighted avg       0.77      0.81      0.77       543

{'average': {'precision': 0.14285714285714285,
  'recall': 0.02702702702702703,
  'f1-score': 0.045454545454545456,
  'support': 37.0},
 'bad': {'precision': 0.7441860465116279,
  'recall': 0.37209302325581395,
  'f1-score': 0.49612403100775193,
  'support': 86.0},
 'good': {'precision': 0.8296146044624746,
  'recall': 0.9738095238095238,
  'f1-score': 0.895947426067908,
  'support': 420.0},
 'accuracy': 0.8139963167587477,
 'macro avg': {'precision': 0.5722192646104151,
  'recall': 0.4576431913641216,
  'f1-score': 0.47917533417673513,
  'support': 543.0},
 'weighted avg': {'precision': 0.7692888548065444,
  'recall': 0.8139963167587477,
  'f1-score': 0.7746710935488144,
  'support': 543.0}}

In [57]:
import joblib

# joblib.dump(log, 'logistic_model.pkl')
# joblib.dump(vectorizer, 'tfidf_vectorizer.pkl')

In [58]:
from sklearn.ensemble import GradientBoostingClassifier

grad_boost = GradientBoostingClassifier(n_estimators=100, random_state=42)
grad_boost.fit(X_train_vec, y_train)

y_pred = grad_boost.predict(X_test_vec)

print("Overall Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Overall Accuracy: 0.8066298342541437

Classification Report:

              precision    recall  f1-score   support

     average       0.17      0.05      0.08        37
         bad       0.71      0.34      0.46        86
        good       0.83      0.97      0.89       420

    accuracy                           0.81       543
   macro avg       0.57      0.45      0.48       543
weighted avg       0.77      0.81      0.77       543

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rand_for = RandomForestClassifier(n_estimators=100, random_state=42, class_weight=custom_weights)

rand_for.fit(X_train_vec, y_train)
y_pred = rand_for.predict(X_test_vec)

print("Overall Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")

Overall Accuracy: 0.8047882136279927

Classification Report:

In [61]:
import mlflow

c:\Users\MY LAPTOP\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [62]:
# Retrieve hyperparameters for the different models used
log_param = log.get_params()

grad_params = grad_boost.get_params()

rf_params = rand_for.get_params()

In [64]:
mlflow.set_tracking_uri("http://127.0.0.1:5000/")
mlflow.set_experiment("First Experiment")

with mlflow.start_run():
  mlflow.log_params(log_param)
  mlflow.log_metrics({
      "Accuracy": report_dict['accuracy'],
      "Good": report_dict['good']['recall'],
      "Average": report_dict['average']['recall'],
      "Bad" : report_dict['bad']['recall'],
      "F1_Score": report_dict['macro avg']['f1-score']
  })
  mlflow.sklearn.log_model(log, "Logistic Regression")

2026/05/13 16:07:35 INFO mlflow.tracking.fluent: Experiment with name 'First Experiment' does not exist. Creating a new experiment.
2026/05/13 16:07:37 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/05/13 16:07:37 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

🏃 View run delightful-deer-452 at: http://127.0.0.1:5000/#/experiments/1/runs/d9e34f72b86a45218536722275683a43
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/1

In [70]:
models = [
    (
        "Logistic Regression",
        LogisticRegression(max_iter=1000, random_state=42, class_weight=custom_weights),
        (X_train_vec, y_train),
        (X_test_vec, y_test)
                                   
    ),
    (
        "Random Forest",
        RandomForestClassifier(n_estimators=100, random_state=42, class_weight=custom_weights),
        (X_train_vec, y_train),
        (X_test_vec, y_test)
    ),
    (
        "Gradient",
        GradientBoostingClassifier(n_estimators=100, random_state=42),
        (X_train_vec, y_train),
        (X_test_vec, y_test)
    )
]

In [75]:
reports = []

for model_name, model, train_set, test_set in models:
    X_train_vec = train_set[0]
    y_train = train_set[1]
    X_test_vec = test_set[0]
    y_test = test_set[1]

    model.fit(X_train_vec, y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test, y_pred, output_dict=True)
    reports.append(report)